IPRANGE   = "192.168.68."

MASTER_NUMBER = 1
MASTER_IP_SUFFIX  = 19

NODE_NUMBER = 1
NODE_IP_SUFFIX  = 24

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"
  config.vm.box_version = "202303.13.0"
  config.vm.box_check_update = false

  (1..MASTER_NUMBER).each do |i|
    config.vm.define "s2-master-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "s2-master-#{i}"
        vb.memory = 4096
        vb.cpus = 2
      end

      node.vm.hostname = "s2-master-#{i}"
      node.vm.network :private_network, ip: IPRANGE + "#{MASTER_IP_SUFFIX + i}"
      node.vm.provision "file", source: "./scripts", destination: "~/scripts"
      node.vm.provision "file", source: "./ssh", destination: "~/ssh"
      node.vm.provision "shell", path: "./setup.sh" do |s|
        s.args = ["master"]
      end
    end
  end

  (1..NODE_NUMBER).each do |i|
    config.vm.define "s2-node-#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "s2-node-#{i}"
        vb.memory = 2048
        vb.cpus = 2
      end

      node.vm.hostname = "s2-node-#{i}"
      node.vm.network :private_network, ip: IPRANGE + "#{NODE_IP_SUFFIX + i}"
      node.vm.provision "file", source: "./ssh", destination: "~/ssh"
      node.vm.provision "shell", path: "./setup.sh" do |s|
        s.args = ["node"]
      end
    end
  end
end
