IPRANGE   = "192.168.68."
IPSUFFIX  = "10"

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-11"
  config.vm.box_version = "202112.19.0"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "docker"
    vb.memory = 2048
    vb.cpus = 1
  end

  config.vm.hostname = "docker"
  config.vm.network :private_network, ip: IPRANGE + IPSUFFIX
  config.vm.provision "file", source: "./scripts", destination: "~/scripts"
  config.vm.provision "shell", path: "./setup.sh"
end
